### ISSUE TITLE
Plugin isn't compatible with UE4.12 or newer

### ISSUE THREAD

**Issue by saidmoya12** [ParcelRot/SpaceNav3D#2]
Plugin isn't compatible with UE4.12

How can I recompile this plugin for support it.

Thanks

**Comment by ParcelRot** [comment]
Compiling plugins requires the ability to also compile the Unreal Engine 4
source code, as far as I know. Epic Games has a wiki for that somewhere.
Good luck.

**Comment by saidmoya12** [comment]
@ParcelRot when I compile i get the error 
```
Cannot open include file "si.h": No such file or directory
```

Any suggest?

thanks

**Comment by saidmoya12** [comment]
I solve it

1. Create a UE4 c++ project (UE4.15 tested)
2. Copy SpaceNav3D to plugins
3. Copy the 3DxWare SDK content to ThirdParty\3DxWare SDK (or reference it)
4. Open Project.sln solution and build it
